export const CREATOR_PROFILE_TABLE = 'creator_profiles';

export const CREATOR_PROFILE_COLUMNS = {
  ID: 'id',
  NAME: 'name',
  LANGUAGE: 'language',
  TARGET_AUDIENCE: 'target_audience',
  STYLE: 'style',
  DURATION: 'duration',
  AVATAR_ID: 'avatar_id',
  VOICE_ID: 'voice_id',
  TONE_NOTES: 'tone_notes',
  COMMON_PHRASES: 'common_phrases',
  TEACHING_STYLE: 'teaching_style',
  HOOK_STYLE: 'hook_style',
  CREATED_AT: 'created_at',
  UPDATED_AT: 'updated_at'
};

export const CREATE_CREATOR_PROFILE_TABLE_SQL = `
  CREATE TABLE IF NOT EXISTS ${CREATOR_PROFILE_TABLE} (
    ${CREATOR_PROFILE_COLUMNS.ID} CHAR(36) PRIMARY KEY,
    ${CREATOR_PROFILE_COLUMNS.NAME} VARCHAR(120) NOT NULL,
    ${CREATOR_PROFILE_COLUMNS.LANGUAGE} VARCHAR(50) DEFAULT 'English',
    ${CREATOR_PROFILE_COLUMNS.TARGET_AUDIENCE} VARCHAR(255) NULL,
    ${CREATOR_PROFILE_COLUMNS.STYLE} VARCHAR(100) NULL,
    ${CREATOR_PROFILE_COLUMNS.DURATION} INT DEFAULT 60,
    ${CREATOR_PROFILE_COLUMNS.AVATAR_ID} VARCHAR(255) NULL,
    ${CREATOR_PROFILE_COLUMNS.VOICE_ID} VARCHAR(255) NULL,
    ${CREATOR_PROFILE_COLUMNS.TONE_NOTES} TEXT NULL,
    ${CREATOR_PROFILE_COLUMNS.COMMON_PHRASES} TEXT NULL,
    ${CREATOR_PROFILE_COLUMNS.TEACHING_STYLE} TEXT NULL,
    ${CREATOR_PROFILE_COLUMNS.HOOK_STYLE} TEXT NULL,
    ${CREATOR_PROFILE_COLUMNS.CREATED_AT} TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ${CREATOR_PROFILE_COLUMNS.UPDATED_AT} TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_creator_profiles_created_at (${CREATOR_PROFILE_COLUMNS.CREATED_AT})
  )
`;
