import { JOB_STATUS } from '../constants/jobStatus.js';

export const VIDEO_PROJECT_TABLE = 'video_projects';

export const VIDEO_PROJECT_COLUMNS = {
  ID: 'id',
  TOPIC: 'topic',
  NOTES: 'notes',
  LANGUAGE: 'language',
  DURATION: 'duration',
  TARGET_AUDIENCE: 'target_audience',
  STYLE: 'style',
  AVATAR_ID: 'avatar_id',
  INPUT_TYPE: 'input_type',
  SOURCE_URL: 'source_url',
  REFERENCE_TEXT: 'reference_text',
  USER_INTENT: 'user_intent',
  ALIGNMENT_DATA: 'alignment_data',
  ANALYSIS_DATA: 'analysis_data',
  SCRIPT_DATA: 'script_data',
  AUDIO_URL: 'audio_url',
  AVATAR_VIDEO_URL: 'avatar_video_url',
  CAPTION_URL: 'caption_url',
  FINAL_VIDEO_URL: 'final_video_url',
  STATUS: 'status',
  ERROR_MESSAGE: 'error_message',
  CREATED_AT: 'created_at',
  UPDATED_AT: 'updated_at'
};

const statusValues = Object.values(JOB_STATUS).map((status) => `'${status}'`).join(', ');

export const VIDEO_PROJECT_INDEXES = {
  STATUS: 'idx_video_projects_status',
  CREATED_AT: 'idx_video_projects_created_at'
};

export const CREATE_VIDEO_PROJECT_TABLE_SQL = `
  CREATE TABLE IF NOT EXISTS ${VIDEO_PROJECT_TABLE} (
    ${VIDEO_PROJECT_COLUMNS.ID} CHAR(36) PRIMARY KEY,
    ${VIDEO_PROJECT_COLUMNS.TOPIC} VARCHAR(255) NOT NULL,
    ${VIDEO_PROJECT_COLUMNS.NOTES} TEXT NULL,
    ${VIDEO_PROJECT_COLUMNS.LANGUAGE} VARCHAR(50) DEFAULT 'English',
    ${VIDEO_PROJECT_COLUMNS.DURATION} INT DEFAULT 60,
    ${VIDEO_PROJECT_COLUMNS.TARGET_AUDIENCE} VARCHAR(255) NULL,
    ${VIDEO_PROJECT_COLUMNS.STYLE} VARCHAR(100) NULL,
    ${VIDEO_PROJECT_COLUMNS.AVATAR_ID} VARCHAR(255) NULL,
    ${VIDEO_PROJECT_COLUMNS.INPUT_TYPE} VARCHAR(50) DEFAULT 'simple_prompt',
    ${VIDEO_PROJECT_COLUMNS.SOURCE_URL} TEXT NULL,
    ${VIDEO_PROJECT_COLUMNS.REFERENCE_TEXT} MEDIUMTEXT NULL,
    ${VIDEO_PROJECT_COLUMNS.USER_INTENT} TEXT NULL,
    ${VIDEO_PROJECT_COLUMNS.ALIGNMENT_DATA} JSON NULL,
    ${VIDEO_PROJECT_COLUMNS.ANALYSIS_DATA} JSON NULL,
    ${VIDEO_PROJECT_COLUMNS.SCRIPT_DATA} JSON NULL,
    ${VIDEO_PROJECT_COLUMNS.AUDIO_URL} TEXT NULL,
    ${VIDEO_PROJECT_COLUMNS.AVATAR_VIDEO_URL} TEXT NULL,
    ${VIDEO_PROJECT_COLUMNS.CAPTION_URL} TEXT NULL,
    ${VIDEO_PROJECT_COLUMNS.FINAL_VIDEO_URL} TEXT NULL,
    ${VIDEO_PROJECT_COLUMNS.STATUS} ENUM(${statusValues}) DEFAULT '${JOB_STATUS.QUEUED}',
    ${VIDEO_PROJECT_COLUMNS.ERROR_MESSAGE} TEXT NULL,
    ${VIDEO_PROJECT_COLUMNS.CREATED_AT} TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ${VIDEO_PROJECT_COLUMNS.UPDATED_AT} TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX ${VIDEO_PROJECT_INDEXES.STATUS} (${VIDEO_PROJECT_COLUMNS.STATUS}),
    INDEX ${VIDEO_PROJECT_INDEXES.CREATED_AT} (${VIDEO_PROJECT_COLUMNS.CREATED_AT})
  )
`;
