import { VIDEO_JOB_COLUMNS, VIDEO_JOB_TABLE } from './VideoJob.model.js';

export const VIDEO_JOB_STEP_TABLE = 'video_job_steps';

export const VIDEO_JOB_STEP_COLUMNS = {
  ID: 'id',
  JOB_ID: 'job_id',
  STEP: 'step',
  STATUS: 'status',
  PROVIDER: 'provider',
  PROVIDER_JOB_ID: 'provider_job_id',
  INPUT_DATA: 'input_data',
  OUTPUT_DATA: 'output_data',
  ERROR_MESSAGE: 'error_message',
  STARTED_AT: 'started_at',
  COMPLETED_AT: 'completed_at',
  CREATED_AT: 'created_at',
  UPDATED_AT: 'updated_at'
};

export const CREATE_VIDEO_JOB_STEP_TABLE_SQL = `
  CREATE TABLE IF NOT EXISTS ${VIDEO_JOB_STEP_TABLE} (
    ${VIDEO_JOB_STEP_COLUMNS.ID} CHAR(36) PRIMARY KEY,
    ${VIDEO_JOB_STEP_COLUMNS.JOB_ID} CHAR(36) NOT NULL,
    ${VIDEO_JOB_STEP_COLUMNS.STEP} VARCHAR(50) NOT NULL,
    ${VIDEO_JOB_STEP_COLUMNS.STATUS} VARCHAR(50) NOT NULL DEFAULT 'pending',
    ${VIDEO_JOB_STEP_COLUMNS.PROVIDER} VARCHAR(50) NULL,
    ${VIDEO_JOB_STEP_COLUMNS.PROVIDER_JOB_ID} VARCHAR(255) NULL,
    ${VIDEO_JOB_STEP_COLUMNS.INPUT_DATA} JSON NULL,
    ${VIDEO_JOB_STEP_COLUMNS.OUTPUT_DATA} JSON NULL,
    ${VIDEO_JOB_STEP_COLUMNS.ERROR_MESSAGE} TEXT NULL,
    ${VIDEO_JOB_STEP_COLUMNS.STARTED_AT} TIMESTAMP NULL,
    ${VIDEO_JOB_STEP_COLUMNS.COMPLETED_AT} TIMESTAMP NULL,
    ${VIDEO_JOB_STEP_COLUMNS.CREATED_AT} TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ${VIDEO_JOB_STEP_COLUMNS.UPDATED_AT} TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE INDEX uq_video_job_steps_job_step (
      ${VIDEO_JOB_STEP_COLUMNS.JOB_ID}, ${VIDEO_JOB_STEP_COLUMNS.STEP}
    ),
    UNIQUE INDEX uq_video_job_steps_provider_job (
      ${VIDEO_JOB_STEP_COLUMNS.PROVIDER}, ${VIDEO_JOB_STEP_COLUMNS.PROVIDER_JOB_ID}
    ),
    INDEX idx_video_job_steps_status (${VIDEO_JOB_STEP_COLUMNS.STATUS}),
    CONSTRAINT fk_video_job_steps_job_id
      FOREIGN KEY (${VIDEO_JOB_STEP_COLUMNS.JOB_ID})
      REFERENCES ${VIDEO_JOB_TABLE}(${VIDEO_JOB_COLUMNS.ID})
      ON DELETE CASCADE
  )
`;
